//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VertexCommands_CS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VertexCommands_CS.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteVertex {
            get {
                object obj = ResourceManager.GetObject("DeleteVertex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vertex (custom).
        /// </summary>
        internal static string DeleteVertex_CommandCaption {
            get {
                return ResourceManager.GetString("DeleteVertex_CommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vertex.
        /// </summary>
        internal static string DeleteVertex_CommandMessage {
            get {
                return ResourceManager.GetString("DeleteVertex_CommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vertex.
        /// </summary>
        internal static string DeleteVertex_CommandToolTip {
            get {
                return ResourceManager.GetString("DeleteVertex_CommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InsertVertex {
            get {
                object obj = ResourceManager.GetObject("InsertVertex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertex (custom).
        /// </summary>
        internal static string InsertVertex_CommandCaption {
            get {
                return ResourceManager.GetString("InsertVertex_CommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertex at clicked location.
        /// </summary>
        internal static string InsertVertex_CommandMessage {
            get {
                return ResourceManager.GetString("InsertVertex_CommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertex at clicked location.
        /// </summary>
        internal static string InsertVertex_CommandToolTip {
            get {
                return ResourceManager.GetString("InsertVertex_CommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OOBDeleteVertex {
            get {
                object obj = ResourceManager.GetObject("OOBDeleteVertex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vertex (out-of-box).
        /// </summary>
        internal static string OOBDeleteVertex_CommandCaption {
            get {
                return ResourceManager.GetString("OOBDeleteVertex_CommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vertex at clicked location using out-of-box command.
        /// </summary>
        internal static string OOBDeleteVertex_CommandMessage {
            get {
                return ResourceManager.GetString("OOBDeleteVertex_CommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vertex at clicked location using out-of-box command.
        /// </summary>
        internal static string OOBDeleteVertex_CommandToolTip {
            get {
                return ResourceManager.GetString("OOBDeleteVertex_CommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OOBInsertVertex {
            get {
                object obj = ResourceManager.GetObject("OOBInsertVertex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertex (out-of-box).
        /// </summary>
        internal static string OOBInsertVertex_CommandCaption {
            get {
                return ResourceManager.GetString("OOBInsertVertex_CommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertex at clicked location using out-of-box command.
        /// </summary>
        internal static string OOBInsertVertex_CommandMessage {
            get {
                return ResourceManager.GetString("OOBInsertVertex_CommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertex at clicked location using out-of-box command.
        /// </summary>
        internal static string OOBInsertVertex_CommandToolTip {
            get {
                return ResourceManager.GetString("OOBInsertVertex_CommandToolTip", resourceCulture);
            }
        }
    }
}
