
// SampleProvider.idl : IDL source for SampleProvider.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SampleProvider.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(43DF0EAD-6303-448D-86E9-594DF15EC84D),
	version(1.0),
	helpstring("SampleProvider 1.0 Type Library")
]
library SAMPLEPROVIDERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(4FE4A56C-386B-4701-A021-11BA959E2EC1),
		helpstring("SampleProv OLE DB Provider")
	]
	coclass SampleProv
	{
		interface IUnknown;
	};
};
