//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timestamper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timestamper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED.
        /// </summary>
        internal static string CreatedFieldKey {
            get {
                return ResourceManager.GetString("CreatedFieldKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string DefaultCreatedField {
            get {
                return ResourceManager.GetString("DefaultCreatedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string DefaultModifiedField {
            get {
                return ResourceManager.GetString("DefaultModifiedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string DefaultUserField {
            get {
                return ResourceManager.GetString("DefaultUserField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save extension properties. Failed to acquire an exclusive lock..
        /// </summary>
        internal static string FailedToSavePropertiesMsg {
            get {
                return ResourceManager.GetString("FailedToSavePropertiesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFIED.
        /// </summary>
        internal static string ModifiedFieldKey {
            get {
                return ResourceManager.GetString("ModifiedFieldKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to modify the timestamp fields:.
        /// </summary>
        internal static string PropertyPageApplyErrorMsg {
            get {
                return ResourceManager.GetString("PropertyPageApplyErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp Settings.
        /// </summary>
        internal static string PropertyPageTitle {
            get {
                return ResourceManager.GetString("PropertyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamped Class.
        /// </summary>
        internal static string TimestampedClassName {
            get {
                return ResourceManager.GetString("TimestampedClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        internal static string UserFieldKey {
            get {
                return ResourceManager.GetString("UserFieldKey", resourceCulture);
            }
        }
    }
}
