//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace TestRasterBuilder
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestRasterBuilder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MyCoclass.
        /// </summary>
        internal static string CoclassName
        {
            get
            {
                return ResourceManager.GetString("CoclassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IMyInterface.
        /// </summary>
        internal static string InterfaceName
        {
            get
            {
                return ResourceManager.GetString("InterfaceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Program.cs.
        /// </summary>
        internal static string SourceFile
        {
            get
            {
                return ResourceManager.GetString("SourceFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MyTable.
        /// </summary>
        internal static string TableName
        {
            get
            {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geodatabase\CS94\Example\MyCoverages\.
        /// </summary>
        internal static string TestDataCoverages
        {
            get
            {
                return ResourceManager.GetString("TestDataCoverages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geodatabase\CS94\Example\MyData.gdb.
        /// </summary>
        internal static string TestDataFGDB
        {
            get
            {
                return ResourceManager.GetString("TestDataFGDB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geodatabase\CS94\Example\MyData.mdb.
        /// </summary>
        internal static string TestDataPGDB
        {
            get
            {
                return ResourceManager.GetString("TestDataPGDB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geodatabase\CS94\Example\MySdcData\.
        /// </summary>
        internal static string TestDataSDC
        {
            get
            {
                return ResourceManager.GetString("TestDataSDC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geodatabase\CS94\Example\MyShapefiles\.
        /// </summary>
        internal static string TestDataShapefiles
        {
            get
            {
                return ResourceManager.GetString("TestDataShapefiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Geodatabase test template..
        /// </summary>
        internal static string TestDescription
        {
            get
            {
                return ResourceManager.GetString("TestDescription", resourceCulture);
            }
        }
    }
}
